project:
  type: website

website:
  title: "Dharmesh D Bhuva"
  navbar:
    left:
      - href: software.qmd
        text: Software
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto